apiVersion: apps/v1
kind: Deployment
metadata:
  name: emotions-api
  labels:
    app: emotions-api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
