apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../base/emotions-api/

commonLabels:
  env: prod

nameSuffix: -prod

patchesStrategicMerge:
  - deployment.yaml

images:
  - name: r1nzler/emotions-api
    newTag: 6f87ef0f