apiVersion: apps/v1
kind: Deployment
metadata:
  name: emotions-api
  labels:
    app: emotions-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emotions-api
  template:
    metadata:
      labels:
        app: emotions-api
    spec:
      containers:
      - name: emotions-api
        image: r1nzler/emotions-api:660a9561
        ports:
        - containerPort: 80
